update

diff --git a/one-cmds/enabled b/one-cmds/enabled
--- a/one-cmds/enabled
+++ b/one-cmds/enabled
@@ -1,19 +1,19 @@
 #!/usr/bin/env bash
 
 set -o errexit -o nounset -o pipefail -o errtrace
-(shopt -p inherit_errexit &> /dev/null) && shopt -s inherit_errexit
+(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit
 
 # one.bash:completion
-if [[ "${1:-}" == --complete ]]; then
-  words=(-h --help --type --priority)
-  printf '%s\n' "${words[@]}"
-  exit 0
+if [[ ${1:-} == --complete ]]; then
+	words=(-h --help --type --priority)
+	printf '%s\n' "${words[@]}"
+	exit 0
 fi
 
 usage() {
-  local cmd
-  cmd=$(basename "$0")
-  cat << EOF
+	local cmd
+	cmd=$(basename "$0")
+	cat <<EOF
 Usage: one $cmd [OPTIONS]
 Desc:  List enabled modules
 Options:
@@ -25,13 +25,13 @@ EOF
 
 # one.bash:usage
 if [[ ${1:-} == -h ]] || [[ ${1:-} == --help ]]; then
-  usage
-  exit 0
+	usage
+	exit 0
 fi
 
 if [[ -z ${ONE_DIR:-} ]]; then
-  SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
-  ONE_DIR="$SCRIPT_DIR/.."
+	SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
+	ONE_DIR="$SCRIPT_DIR/.."
 fi
 
 # shellcheck source=./base-scripts.bash
@@ -54,46 +54,46 @@ printf 'Prio Type %-18s %-18s %s\n' "Name" "Repo" "About"
 find "$ONE_DIR/enabled" -maxdepth 1 -name "*---*.bash" | print_list_item | sort
 
 trim_str() {
-  local str=$1 len=$2 n
-  n=$((len - 2))
+	local str=$1 len=$2 n
+	n=$((len - 2))
 
-  if ((${#str} > len)); then
-    printf '%s..' "${str:0:$n}"
-  else
-    printf '%s' "${str}"
-  fi
+	if ((${#str} > len)); then
+		printf '%s..' "${str:0:n}"
+	else
+		printf '%s' "${str}"
+	fi
 }
 
 list() {
-  local type=$1 folder=$2 type_color=$3
+	local type=$1 folder=$2 type_color=$3
 
-  shopt -s nullglob
-  local path repo name link repo_name
+	shopt -s nullglob
+	local path repo name link repo_name
 
-  for path in "$ONE_DIR/enabled/$type"/*; do
-    name=$(basename "$path")
-    link=$(readlink "$path")
-    repo="$(dirname "$(dirname "$link")")"
-    if [[ ! -f $repo/one.repo.bash ]]; then
-      repo="$(dirname "$(dirname "$repo")")"
-    fi
-    repo_name=$(basename "$repo")
-    printf '     %b%-4s %b%-18s %b%-18s' "$type_color" "${type^}" "$CYAN" "$(trim_str "$name" 18)" "$BLUE" "$(trim_str "$repo_name" 18)"
+	for path in "$ONE_DIR/enabled/$type"/*; do
+		name=$(basename "$path")
+		link=$(readlink "$path")
+		repo="$(dirname "$(dirname "$link")")"
+		if [[ ! -f $repo/one.repo.bash ]]; then
+			repo="$(dirname "$(dirname "$repo")")"
+		fi
+		repo_name=$(basename "$repo")
+		printf '     %b%-4s %b%-18s %b%-18s' "$type_color" "${type^}" "$CYAN" "$(trim_str "$name" 18)" "$BLUE" "$(trim_str "$repo_name" 18)"
 
-    if [[ -f $repo/$folder/$name.opt.bash ]]; then
-      (
-        # shellcheck disable=1090
-        source "$repo/$folder/$name.opt.bash"
-        printf '%b%s' "$WHITE" "${ABOUT:-}"
-      )
-    elif [[ -f $repo/$folder/$name ]]; then
-      printf '%b%s' "$WHITE" "$(metafor about-plugin < "$repo/$folder/$name")"
-    else
-      printf '%b%s' "$WHITE" '<ERROR>'
-    fi
+		if [[ -f $repo/$folder/$name.opt.bash ]]; then
+			(
+				# shellcheck disable=1090
+				source "$repo/$folder/$name.opt.bash"
+				printf '%b%s' "$WHITE" "${ABOUT:-}"
+			)
+		elif [[ -f $repo/$folder/$name ]]; then
+			printf '%b%s' "$WHITE" "$(metafor about-plugin <"$repo/$folder/$name")"
+		else
+			printf '%b%s' "$WHITE" '<ERROR>'
+		fi
 
-    printf '\n'
-  done
+		printf '\n'
+	done
 }
 
 list bin bins "$WHITE"
diff --git a/one-cmds/help b/one-cmds/help
--- a/one-cmds/help
+++ b/one-cmds/help
@@ -5,7 +5,7 @@ set -o errexit -o nounset -o pipefail -o errtrace
 
 # one.bash:usage:-h
 if (($# == 0)) || [[ $1 == -h ]] || [[ $1 == --help ]]; then
-  cat <<EOF
+	cat <<EOF
 Usage: one help [<CMD>]
        one help -a
 
@@ -19,62 +19,62 @@ Arguments:
 Options:
   -a, --all     If set, print all command usages.
 EOF
-  exit 0
+	exit 0
 fi
 
 if [[ -z ${ONE_DIR:-} ]]; then
-  SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
-  readonly SCRIPT_DIR
-  ONE_DIR=$SCRIPT_DIR/..
+	SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
+	readonly SCRIPT_DIR
+	ONE_DIR=$SCRIPT_DIR/..
 fi
 
 # one.bash:completion
 if [[ $1 == '--complete' ]]; then
-  if (($# == 2)); then
-    "$ONE_DIR"/one-cmds/commands
-  fi
-  exit 0
+	if (($# == 2)); then
+		"$ONE_DIR"/one-cmds/commands
+	fi
+	exit 0
 fi
 
 print_help() {
-  local cmd="$1"
-  local file="$ONE_DIR/one-cmds/$cmd"
-  local label arg
+	local cmd="$1"
+	local file="$ONE_DIR/one-cmds/$cmd"
+	local label arg
 
-  if [[ -x $ONE_DIR/one-cmds/$cmd/main ]]; then
-    file="$ONE_DIR/one-cmds/$cmd/main"
-  elif [[ ! -x "${file}" ]]; then
-    printf '%bNot found command "%s".%b\n' "$YELLOW" "$cmd" "$RESET_ALL" >&2
-    return "$ONE_EX_USAGE"
-  fi
+	if [[ -x $ONE_DIR/one-cmds/$cmd/main ]]; then
+		file="$ONE_DIR/one-cmds/$cmd/main"
+	elif [[ ! -x ${file} ]]; then
+		printf '%bNot found command "%s".%b\n' "$YELLOW" "$cmd" "$RESET_ALL" >&2
+		return "$ONE_EX_USAGE"
+	fi
 
-  label=$(grep -i '^# one.bash:usage' "$file" 2>/dev/null || true)
+	label=$(grep -i '^# one.bash:usage' "$file" 2>/dev/null || true)
 
-  if [[ -z "$label" ]]; then
-    printf '%bThe command "%s" has not usage document.%b\n' "$YELLOW" "$cmd" "$RESET_ALL" >&2
-    return "$ONE_EX_UNAVAILABLE"
-  fi
+	if [[ -z $label ]]; then
+		printf '%bThe command "%s" has not usage document.%b\n' "$YELLOW" "$cmd" "$RESET_ALL" >&2
+		return "$ONE_EX_UNAVAILABLE"
+	fi
 
-  arg=$(sed -E 's/^# one.bash:usage(:?.*)/\1/i' <<<"$label" || true)
+	arg=$(sed -E 's/^# one.bash:usage(:?.*)/\1/i' <<<"$label" || true)
 
-  if [[ -z ${arg#:} ]]; then
-    arg='--help'
-  else
-    arg=${arg#:}
-  fi
+	if [[ -z ${arg#:} ]]; then
+		arg='--help'
+	else
+		arg=${arg#:}
+	fi
 
-  "$file" "$arg"
+	"$file" "$arg"
 }
 
 main() {
-  # shellcheck source=./base-scripts.bash
-  . "$ONE_DIR/one-cmds/base-scripts.bash"
+	# shellcheck source=./base-scripts.bash
+	. "$ONE_DIR/one-cmds/base-scripts.bash"
 
-  if [[ $1 == -a ]] || [[ $1 == --all ]]; then
-    one -h
-  else
-    print_help "$1"
-  fi
+	if [[ $1 == -a ]] || [[ $1 == --all ]]; then
+		one -h
+	else
+		print_help "$1"
+	fi
 }
 
 main "$@"
